language: java
jdk: openjdk11
dist: trusty
install: true
script:
  - "mvn cobertura:cobertura"
  - "mvn clean install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2